// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktop$0 from "../../internal/adapter/in/desktop/models.js";

export function SetStatus(status: string): $CancellablePromise<void> {
    return $Call.ByID(4081117397, status);
}

export function Snapshot(): $CancellablePromise<desktop$0.Snapshot> {
    return $Call.ByID(431882765).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = desktop$0.Snapshot.createFrom;
