package builtin

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/projectTHORN/proton/internal/tool"
)

func TestWriteFilePermissionDetailShowsManagedFile(t *testing.T) {
	ws := newTestWorkspace(t, nil)
	h := NewWriteFile(ws, &recordingCheckpointStore{id: "managed"})
	provider := h.(tool.DetailProvider)
	args, _ := json.Marshal(map[string]any{
		"file_path": "api/service.go",
		"content":   "// Code generated by x. DO NOT EDIT.\npackage api\n",
	})
	if got := provider.PermissionDetail(args); got != "api/service.go · generated file" {
		t.Fatalf("PermissionDetail() = %q", got)
	}
}

func TestSearchReplacePermissionDetailShowsLockfile(t *testing.T) {
	ws := newTestWorkspace(t, nil)
	h := NewSearchReplace(ws, &recordingCheckpointStore{id: "managed"})
	provider := h.(tool.DetailProvider)
	args, _ := json.Marshal(map[string]any{"file_path": "pnpm-lock.yaml"})
	if got := provider.PermissionDetail(args); got != "pnpm-lock.yaml · lockfile" {
		t.Fatalf("PermissionDetail() = %q", got)
	}
}

func TestApplyPatchPermissionDetailShowsManagedPaths(t *testing.T) {
	ws := newTestWorkspace(t, nil)
	h := NewApplyPatch(ws, &recordingCheckpointStore{id: "managed"})
	provider := h.(tool.DetailProvider)
	patch := `*** Begin Patch
*** Add File: vendor/pkg/a.go
+package pkg
*** Add File: src/app.go
+package src
*** End Patch`
	args, _ := json.Marshal(map[string]any{"patch": patch})
	got := provider.PermissionDetail(args)
	if !strings.Contains(got, "vendor/pkg/a.go · vendored file") {
		t.Fatalf("PermissionDetail() = %q, want vendored label", got)
	}
	if !strings.Contains(got, "src/app.go") {
		t.Fatalf("PermissionDetail() = %q, want regular path", got)
	}
}
