package workspace

import "testing"

func TestClassifyManagedPath(t *testing.T) {
	tests := map[string]ManagedFileKind{
		"pkg/foo.go":                ManagedFileRegular,
		"vendor/lib/foo.go":         ManagedFileVendored,
		"src/vendorish/foo.go":      ManagedFileRegular,
		"node_modules/pkg/index.js": ManagedFileDependency,
		"package-lock.json":         ManagedFileLockfile,
		"nested/pnpm-lock.yaml":     ManagedFileLockfile,
		"api/service.pb.go":         ManagedFileGenerated,
		"internal/schema.gen.go":    ManagedFileGenerated,
		"internal/foo_generated.go": ManagedFileGenerated,
		"web/client.generated.ts":   ManagedFileGenerated,
	}
	for path, want := range tests {
		if got := ClassifyManagedPath(path); got != want {
			t.Fatalf("ClassifyManagedPath(%q) = %q, want %q", path, got, want)
		}
	}
}

func TestHasGeneratedHeader(t *testing.T) {
	if !HasGeneratedHeader([]byte("// Code generated by protoc. DO NOT EDIT.\n")) {
		t.Fatal("generated header not detected")
	}
	if HasGeneratedHeader([]byte("// generated helper; safe to edit\n")) {
		t.Fatal("generated word without do-not-edit marker was classified")
	}
	large := make([]byte, 5000)
	copy(large[4500:], []byte("generated DO NOT EDIT"))
	if HasGeneratedHeader(large) {
		t.Fatal("marker beyond bounded header probe was classified")
	}
}
